# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20170828_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_de_inscricao', models.DateField(blank=True, null=True)),
                ('preco', models.FloatField()),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='eventos.Evento')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoafisic', to='eventos.PessoaFisica')),
            ],
        ),
    ]
